project_name: vint-release
run_name: vint-5c

# training setup
use_wandb: True # set to false if you don't want to log to wandb
train: False
batch_size: 64
epochs: 30
gpu_ids: [0]
num_workers: 8
lr: 5e-4
optimizer: adamw
clipping: False
max_norm: 1.
scheduler: "cosine"
warmup: True 
warmup_epochs: 3
cyclic_period: 10
plateau_patience: 3
plateau_factor: 0.5
seed: 0
load_run: vint-release/vint-5c_2025_03_23_04_37_02

early_stopping: False
early_stopping_patience: 20  # or 10
scheduler_monitor: dist_loss  # or total_loss
# model params
model_type: vint
obs_encoder: "efficientnet-b0" # by default, this is imagenet pretrained
obs_encoding_size: 512
mha_num_attention_heads: 4
mha_num_attention_layers: 4
mha_ff_dim_factor: 4
late_fusion: False

# normalization for the action space
normalize: True

# context
context_type: temporal
context_size: 5
# tradeoff between action and distance prediction loss
alpha: 0.5

# distance bounds for distance and action and distance predictions 
distance:
  min_dist_cat: 0
  max_dist_cat: 20
action:
  min_dist_cat: 0
  max_dist_cat: 10
close_far_threshold: 10 # distance threshold used to separate the close and far subgoals that are sampled per datapoint

# action output params
len_traj_pred: 5
learn_angle: True

# dataset specific parameters
image_size: [128, 128] # width, height
goal_type: "image"

datasets:
   nuScenes_custom:
     data_folder: vint_train/data/nu_output
     train: vint_train/data/data_splits/nuScenes_custom/train/
     test: vint_train/data/data_splits/nuScenes_custom/test/
     end_slack: 3
     goals_per_obs: 1
     negative_mining: True
    
    
   idd_multi:
     data_folder: vint_train/data/idd_multi
     train: vint_train/data/data_splits/idd_multi/train/
     test: vint_train/data/data_splits/idd_multi/test/
     end_slack: 3
     goals_per_obs: 1
     negative_mining: True
    
  
   waymo_vint:
    data_folder: vint_train/data/waymo_vint
    train: vint_train/data/data_splits/waymo_vint/train/
    test: vint_train/data/data_splits/waymo_vint/test/
    end_slack: 3
    goals_per_obs: 1
    negative_mining: True
    

  # Commenting out unused datasets
  # recon:
  #   data_folder: /home/<username>/vint_dataset/recon
  #   train: /home/<username>/data_splits/recon/train/
  #   test: /home/<username>/data_splits/recon/test/
  #   end_slack: 3
  #   goals_per_obs: 1
  #   negative_mining: True

  # go_stanford:
  #   data_folder: /home/<username>/vint_dataset/go_stanford_cropped
  #   train: /home/<username>/data_splits/go_stanford/train/
  #   test: /home/<username>/data_splits/go_stanford/test/
  #   end_slack: 0
  #   goals_per_obs: 2
  #   negative_mining: True

  # cory_hall:
  #   data_folder: /home/<username>/vint_dataset/cory_hall/
  #   train: /home/<username>/data_splits/cory_hall/train/
  #   test: /home/<username>/data_splits/cory_hall/test/
  #   end_slack: 3
  #   goals_per_obs: 1
  #   negative_mining: True

  # tartan_drive:
  #   data_folder: /home/<username>/vint_dataset/tartan_drive/
  #   train: /home/<username>/data_splits/tartan_drive/train/
  #   test: /home/<username>/data_splits/tartan_drive/test/
  #   end_slack: 3
  #   goals_per_obs: 1
  #   negative_mining: True

  # sacson:
  #   data_folder: /home/<username>/vint_dataset/sacson/
  #   train: /home/<username>/data_splits/sacson/train/
  #   test: /home/<username>/data_splits/sacson/test/
  #   end_slack: 3
  #   goals_per_obs: 1
  #   negative_mining: True

  # Private datasets (uncomment if needed)
  # seattle:
  #   data_folder: /home/<username>/vint_dataset/seattle/
  #   train: /home/<username>/data_splits/seattle/train/
  #   test: /home/<username>/data_splits/seattle/test/
  #   end_slack: 0
  #   goals_per_obs: 1
  #   negative_mining: True

  # scand:
  #   data_folder: /home/<username>/vint_dataset/scand/
  #   train: /home/<username>/data_splits/scand/train/
  #   test: /home/<username>/data_splits/scand/test/
  #   end_slack: 0
  #   goals_per_obs: 1
  #   negative_mining: True

# logging stuff
## =0 turns off
print_log_freq: 100 # in iterations
image_log_freq: 1000 #0 # in iterations
num_images_log: 8 #0 
pairwise_test_freq: 0 # in epochs
eval_fraction: 0.25
wandb_log_freq: 10 # in iterations
eval_freq: 1 # in epochs
